<?php
defined('BASEPATH') OR exit('No direct script access allowed');
/**
* Nama Modul      : Model Realisasi Penerimaan Per Kelurahan
* Dibuat Oleh     : Endang Kurniawan
* Dibuat Tanggal  : 2017-09-04
* Selesai Tanggal : -
*/

class M_realisasi_per_kelurahan extends CI_model {
	private $dbOracle;
	public function __construct(){
		parent::__construct();
		$this->dbOracle = $this->load->database('oracle', TRUE);
	}

 function getPembayaran($PeriodeAwal, $PeriodeAkhir, $KodeKec, $JenisBuku){
	 if($JenisBuku == '0'){
		$BatasBuku = " > 0";
	 }elseif($JenisBuku=='1'){
		 $BatasBuku = " < 2000000";
	 }else{
		 $BatasBuku = " >= 2000000";
	 }
	 $xPeriodeAwal = explode('-',$PeriodeAwal);
	 $Tahun = $xPeriodeAwal[0];
	 $sql = "SELECT RKL.KD_KELURAHAN, RKL.NM_KELURAHAN, T1.WP_POKOK_PERIODE_LALU, T1.POKOK_PERIODE_LALU, T1.WP_TUNGGAKAN_PERIODE_LALU, 
				T1.TUNGGAKAN_PERIODE_LALU, T1.WP_POKOK_PERIODE_INI, T1.POKOK_PERIODE_INI, T1.WP_TUNGGAKAN_PERIODE_INI, T1.TUNGGAKAN_PERIODE_INI, 
				T1.WP_POKOK, T1.POKOK, T1.WP_TUNGGAKAN, T1.TUNGGAKAN, T1.REALISASI, T1.DENDA, T.POKOK AS TARGET, T.WP_POKOK AS WP_TARGET, RKC.KD_KECAMATAN, 
				RKC.NM_KECAMATAN
			FROM REF_KELURAHAN RKL
			LEFT JOIN (
				SELECT MAX(PBS.KD_KELURAHAN) AS KD_KELURAHAN,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT < TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_POKOK_PERIODE_LALU,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT < TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS POKOK_PERIODE_LALU,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT < TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_TUNGGAKAN_PERIODE_LALU,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT < TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS TUNGGAKAN_PERIODE_LALU,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_POKOK_PERIODE_INI,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS POKOK_PERIODE_INI,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_TUNGGAKAN_PERIODE_INI,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD') AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS TUNGGAKAN_PERIODE_INI,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_POKOK,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT = 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS POKOK,
				COUNT(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS WP_TUNGGAKAN,
				SUM(
					CASE WHEN 
						PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') AND PBS.DENDA_SPPT > 0 
					THEN 
						(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT)
					END
				) AS TUNGGAKAN,
				SUM(PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) AS REALISASI,
				SUM(PBS.DENDA_SPPT) AS DENDA
				FROM PEMBAYARAN_SPPT PBS 
					WHERE EXTRACT(YEAR FROM PBS.TGL_PEMBAYARAN_SPPT) = '$Tahun'
					AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD')
					AND PBS.KD_KECAMATAN = '$KodeKec'
					AND (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) $BatasBuku
					GROUP BY PBS.KD_KELURAHAN
					ORDER BY PBS.KD_KELURAHAN
			) T1
			ON RKL.KD_KELURAHAN = T1.KD_KELURAHAN
		LEFT JOIN (
			SELECT MAX(S.KD_KELURAHAN) AS KD_KELURAHAN, SUM(S.PBB_YG_HARUS_DIBAYAR_SPPT) AS POKOK, COUNT(S.PBB_YG_HARUS_DIBAYAR_SPPT) AS WP_POKOK FROM SPPT S WHERE S.KD_KECAMATAN = '$KodeKec' AND S.THN_PAJAK_SPPT = '$Tahun' AND S.PBB_YG_HARUS_DIBAYAR_SPPT $BatasBuku GROUP BY S.KD_KELURAHAN
		) T
		ON RKL.KD_KELURAHAN = T.KD_KELURAHAN
		LEFT JOIN REF_KECAMATAN RKC
		ON RKL.KD_KECAMATAN = RKC.KD_KECAMATAN
		WHERE RKL.KD_KECAMATAN = '$KodeKec'
		ORDER BY RKL.KD_KELURAHAN";
	$query = $this->dbOracle->query($sql);
	if($query->num_rows()>0){
		return $query->result_array();
	}
 }
}