<?php
/**
* Nama Modul      : Model List Bayar
* Dibuat Oleh     : Endang Kurniawan
* Dibuat Tanggal  : 2017-07-26
* Selesai Tanggal : -
*/

class M_list_bayar extends CI_Model{
	private $dbOracle;
	public function __construct(){
		parent::__construct();
		$this->dbOracle = $this->load->database('oracle', TRUE);
	}
	
	public function getListKel($KodeKecamatan){
		$sql = "SELECT * FROM REF_KELURAHAN RKL WHERE RKL.KD_KECAMATAN = '$KodeKecamatan'";
		$query = $this->dbOracle->query($sql);
		if($query->num_rows()>0){
			return $query->result_array();
		}		
	}
	
	public function getNamaKec($KodeKecamatan){
		$sql = "SELECT * FROM REF_KECAMATAN RKC WHERE RKC.KD_KECAMATAN = '$KodeKecamatan'";
		$query = $this->dbOracle->query($sql);
		if($query->num_rows()>0){
			return $query->result_array();
		}		
	}
	
	public function getNamaKel($KodeKecamatan, $KodeKelurahan){
		$sql = "SELECT * FROM REF_KELURAHAN RKL WHERE RKL.KD_KECAMATAN = '$KodeKecamatan' AND RKL.KD_KELURAHAN = '$KodeKelurahan'";
		$query = $this->dbOracle->query($sql);
		if($query->num_rows()>0){
			return $query->result_array();
		}		
	}
	
	//periksa login data pada database
	public function generateReport($PeriodeAwal, $PeriodeAkhir, $KodeKecamatan, $KodeKelurahan){
		if($KodeKecamatan=='000'){
			$sql = "SELECT PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||
					PBS.KD_JNS_OP AS NOP, S.NM_WP_SPPT, S.JLN_WP_SPPT, S.BLOK_KAV_NO_WP_SPPT, S.RT_WP_SPPT, S.RW_WP_SPPT, S.KELURAHAN_WP_SPPT, S.KOTA_WP_SPPT,
					DOP.JALAN_OP, DOP.BLOK_KAV_NO_OP, DOP.RT_OP, DOP.RW_OP, RKC.NM_KECAMATAN AS NM_KECAMATAN_OP, RKL.NM_KELURAHAN AS NM_KELURAHAN_OP,
					PBS.THN_PAJAK_SPPT, CASE WHEN PBS.DENDA_SPPT = 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS POKOK, 
					CASE WHEN PBS.DENDA_SPPT <> 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS TUNGGAKAN, PBS.DENDA_SPPT, 
					PBS.KD_TP, TPB.NM_TP, PBS.TGL_PEMBAYARAN_SPPT
						FROM PEMBAYARAN_SPPT PBS
						LEFT JOIN TEMPAT_PEMBAYARAN TPB
						ON PBS.KD_TP = TPB.KD_TP
						LEFT JOIN SPPT S
						ON S.KD_PROPINSI||'.'||S.KD_DATI2||'.'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'.'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP ||'.'|| S.THN_PAJAK_SPPT = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP ||'.'|| PBS.THN_PAJAK_SPPT
						LEFT JOIN DAT_OBJEK_PAJAK DOP
						ON DOP.KD_PROPINSI||'.'||DOP.KD_DATI2||'.'||DOP.KD_KECAMATAN||'.'||DOP.KD_KELURAHAN||'.'||DOP.KD_BLOK||'.'||DOP.NO_URUT||'.'||DOP.KD_JNS_OP = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP
						LEFT JOIN REF_KECAMATAN RKC
						ON RKC.KD_KECAMATAN = PBS.KD_KECAMATAN
						LEFT JOIN REF_KELURAHAN RKL
						ON RKL.KD_KECAMATAN = PBS.KD_KECAMATAN
						AND RKL.KD_KELURAHAN = PBS.KD_KELURAHAN
						WHERE PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD')
						AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD') 
						ORDER BY PBS.KD_KECAMATAN, PBS.KD_KELURAHAN, PBS.KD_BLOK, PBS.NO_URUT, PBS.THN_PAJAK_SPPT";
		}else{
			if($KodeKelurahan=='000'){
			$sql = "SELECT PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||
					PBS.KD_JNS_OP AS NOP, S.NM_WP_SPPT, S.JLN_WP_SPPT, S.BLOK_KAV_NO_WP_SPPT, S.RT_WP_SPPT, S.RW_WP_SPPT, S.KELURAHAN_WP_SPPT, S.KOTA_WP_SPPT,
					DOP.JALAN_OP, DOP.BLOK_KAV_NO_OP, DOP.RT_OP, DOP.RW_OP, RKC.NM_KECAMATAN AS NM_KECAMATAN_OP, RKL.NM_KELURAHAN AS NM_KELURAHAN_OP,
					PBS.THN_PAJAK_SPPT, CASE WHEN PBS.DENDA_SPPT = 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS POKOK, 
					CASE WHEN PBS.DENDA_SPPT <> 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS TUNGGAKAN, PBS.DENDA_SPPT, 
					PBS.KD_TP, TPB.NM_TP, PBS.TGL_PEMBAYARAN_SPPT
						FROM PEMBAYARAN_SPPT PBS
						LEFT JOIN TEMPAT_PEMBAYARAN TPB
						ON PBS.KD_TP = TPB.KD_TP
						LEFT JOIN SPPT S
						ON S.KD_PROPINSI||'.'||S.KD_DATI2||'.'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'.'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP ||'.'|| S.THN_PAJAK_SPPT = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP ||'.'|| PBS.THN_PAJAK_SPPT
						LEFT JOIN DAT_OBJEK_PAJAK DOP
						ON DOP.KD_PROPINSI||'.'||DOP.KD_DATI2||'.'||DOP.KD_KECAMATAN||'.'||DOP.KD_KELURAHAN||'.'||DOP.KD_BLOK||'.'||DOP.NO_URUT||'.'||DOP.KD_JNS_OP = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP
						LEFT JOIN REF_KECAMATAN RKC
						ON RKC.KD_KECAMATAN = PBS.KD_KECAMATAN
						LEFT JOIN REF_KELURAHAN RKL
						ON RKL.KD_KECAMATAN = PBS.KD_KECAMATAN
						AND RKL.KD_KELURAHAN = PBS.KD_KELURAHAN
						WHERE PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD')
						AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD')
						AND PBS.KD_KECAMATAN = '$KodeKecamatan' 
						ORDER BY PBS.KD_KECAMATAN, PBS.KD_KELURAHAN, PBS.KD_BLOK, PBS.NO_URUT, PBS.THN_PAJAK_SPPT";
			}else{
			$sql = "SELECT PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||
					PBS.KD_JNS_OP AS NOP, S.NM_WP_SPPT, S.JLN_WP_SPPT, S.BLOK_KAV_NO_WP_SPPT, S.RT_WP_SPPT, S.RW_WP_SPPT, S.KELURAHAN_WP_SPPT, S.KOTA_WP_SPPT,
					DOP.JALAN_OP, DOP.BLOK_KAV_NO_OP, DOP.RT_OP, DOP.RW_OP, RKC.NM_KECAMATAN AS NM_KECAMATAN_OP, RKL.NM_KELURAHAN AS NM_KELURAHAN_OP,
					PBS.THN_PAJAK_SPPT, CASE WHEN PBS.DENDA_SPPT = 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS POKOK, 
					CASE WHEN PBS.DENDA_SPPT <> 0 THEN (PBS.JML_SPPT_YG_DIBAYAR - PBS.DENDA_SPPT) END AS TUNGGAKAN, PBS.DENDA_SPPT, 
					PBS.KD_TP, TPB.NM_TP, PBS.TGL_PEMBAYARAN_SPPT
						FROM PEMBAYARAN_SPPT PBS
						LEFT JOIN TEMPAT_PEMBAYARAN TPB
						ON PBS.KD_TP = TPB.KD_TP
						LEFT JOIN SPPT S
						ON S.KD_PROPINSI||'.'||S.KD_DATI2||'.'||S.KD_KECAMATAN||'.'||S.KD_KELURAHAN||'.'||S.KD_BLOK||'.'||S.NO_URUT||'.'||S.KD_JNS_OP ||'.'|| S.THN_PAJAK_SPPT = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP ||'.'|| PBS.THN_PAJAK_SPPT
						LEFT JOIN DAT_OBJEK_PAJAK DOP
						ON DOP.KD_PROPINSI||'.'||DOP.KD_DATI2||'.'||DOP.KD_KECAMATAN||'.'||DOP.KD_KELURAHAN||'.'||DOP.KD_BLOK||'.'||DOP.NO_URUT||'.'||DOP.KD_JNS_OP = 
							PBS.KD_PROPINSI||'.'||PBS.KD_DATI2||'.'||PBS.KD_KECAMATAN||'.'||PBS.KD_KELURAHAN||'.'||PBS.KD_BLOK||'.'||PBS.NO_URUT||'.'||PBS.KD_JNS_OP
						LEFT JOIN REF_KECAMATAN RKC
						ON RKC.KD_KECAMATAN = PBS.KD_KECAMATAN
						LEFT JOIN REF_KELURAHAN RKL
						ON RKL.KD_KECAMATAN = PBS.KD_KECAMATAN
						AND RKL.KD_KELURAHAN = PBS.KD_KELURAHAN
						WHERE PBS.TGL_PEMBAYARAN_SPPT >= TO_DATE('$PeriodeAwal','YYYY-MM-DD')
						AND PBS.TGL_PEMBAYARAN_SPPT <= TO_DATE('$PeriodeAkhir','YYYY-MM-DD')
						AND PBS.KD_KECAMATAN = '$KodeKecamatan'
						AND PBS.KD_KELURAHAN = '$KodeKelurahan' 
						ORDER BY PBS.KD_KECAMATAN, PBS.KD_KELURAHAN, PBS.KD_BLOK, PBS.NO_URUT, PBS.THN_PAJAK_SPPT";
			}
		}
		$query = $this->dbOracle->query($sql);
		if($query->num_rows()>0){
			return $query->result_array();
		}
	}
}
?>